# -*- coding: utf-8 -*-
"""yoloGender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rWcbn23elQWqg4_XqSMla2Dz_jLify7
"""

!pip install roboflow

!pip install ultralytics

from roboflow import Roboflow
rf = Roboflow(api_key="z0PLJwf63LAHY28nzc2r")
project = rf.workspace("generalstuff").project("women-men")
version = project.version(1)
dataset = version.download("yolov8")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

result = model.train(
    data = "/content/Women/Men-1/data.yaml",
    epochs = 30,
    imgsz=416,
    batch=16,
    workers=2
)

import os
import matplotlib.pyplot as plt
from PIL import Image
import random # Import the random module

test_path = "/content/Women/Men-1/test/images"

# Get all image paths and then select 6 random ones
all_test_images = [os.path.join(test_path, img) for img in os.listdir(test_path) if img.lower().endswith(('.png', '.jpg', '.jpeg'))]
# Ensure there are at least 6 images to sample, otherwise take all available
num_samples = min(6, len(all_test_images))
test_img = random.sample(all_test_images, num_samples)

plt.figure(figsize=(12,10))

for i, img_path in enumerate(test_img):
    results = model.predict(img_path, show=False)

    # Ambil hasil prediksi sebagai PIL
    pred_img = results[0].plot()  # Numpy array with boxes drawn
    pred_img = Image.fromarray(pred_img)

    # Plot ke grid
    plt.subplot(3, 2, i + 1)
    plt.imshow(pred_img)
    plt.title(os.path.basename(img_path))
    plt.axis("off")

plt.tight_layout()
plt.show()

import os

base_dir = "runs/detect/train2/weights" # Corrected path
print(os.listdir(base_dir))

new_model = YOLO(base_dir + "/best.pt")
new_model.save("gender-cls.pt")

import matplotlib.image as mpimg

img = mpimg.imread("runs/detect/train2/results.png")
plt.figure(figsize=(10, 6))
plt.imshow(img)
plt.axis("off")
plt.title("Training Loss Curve")
plt.show()

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

cm_img = mpimg.imread("runs/detect/train/confusion_matrix.png")
plt.figure(figsize=(8, 8))
plt.imshow(cm_img)
plt.axis("off")
plt.title("Confusion Matrix")
plt.show()

import os
import cv2
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
from ultralytics import YOLO

model = YOLO("gender-cls.pt")

test_img_dir = "/content/Women/Men-1/test/images"
test_lbl_dir = "/content/Women/Men-1/test/labels"

y_true = []
y_pred = []

# Load all test images
for fname in os.listdir(test_img_dir):
    if not fname.endswith(('.jpg', '.jpeg', '.png')):
        continue

    img_path = os.path.join(test_img_dir, fname)
    # Robustly get label path regardless of image extension
    lbl_path = os.path.join(test_lbl_dir, os.path.splitext(fname)[0] + ".txt")

    gt_classes_for_image = []
    # Ground truth (if label file exists)
    if os.path.exists(lbl_path):
        with open(lbl_path, "r") as f:
            for line in f:
                cls = int(line.split()[0])
                gt_classes_for_image.append(cls)

    predicted_classes_for_image = []
    # Prediction
    results = model(img_path)[0]
    for box in results.boxes:
        pred_cls = int(box.cls[0])
        predicted_classes_for_image.append(pred_cls)

    # --- Fix for inconsistent sample count: Align y_true and y_pred for classification report ---
    # This simplified alignment assumes a one-to-one correspondence based on count.
    # A more robust evaluation for object detection requires IoU-based matching and handles
    # false positives/negatives explicitly. Here, we only compare matching counts.
    num_gt = len(gt_classes_for_image)
    num_pred = len(predicted_classes_for_image)

    min_count = min(num_gt, num_pred)

    y_true.extend(gt_classes_for_image[:min_count])
    y_pred.extend(predicted_classes_for_image[:min_count])
    # --- End of fix ---

# Print sklearn report
print("\n=== CLASSIFICATION REPORT ===")
# The lists should now have consistent lengths due to the alignment logic
if len(y_true) == 0: # Handle case where no valid data was collected
    print("No data available for classification report after alignment.")
else:
    print(classification_report(y_true, y_pred, target_names=model.names.values()))

# Confusion Matrix (numerical)
print("\n=== CONFUSION MATRIX ===")
if len(y_true) == 0:
    print("No data available for confusion matrix after alignment.")
else:
    print(confusion_matrix(y_true, y_pred))

from ultralytics import YOLO

model = YOLO("gender-cls.pt")

metrics = model.val(data="/content/Women/Men-1/data.yaml", split="test")
print(metrics)

import glob

wrong = []

for txt in glob.glob("/content/Dataset/train/labels/*.txt"):
    with open(txt) as f:
        for line in f:
            cls = int(line.split()[0])
            if cls not in [0, 1]:   # class valid cuma 0 dan 1
                wrong.append((txt, cls))

print("Train errors:", wrong)

r = model.val()
print(r.confusion_matrix.matrix)
print(r.names)

!rm -rf /content/Women/Men-1/train/cache
!rm -rf /content/Women/Men-1/val/cache
!rm -rf /content/Women/Men-1/test/cache

